# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euclid', '0003_auto_20160304_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
