# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('euclid', '0005_auto_20160304_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solved_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='euclid.UserProfile'),
        ),
    ]
