# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('euclid', '0006_question_solved_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='solved_by_user',
        ),
    ]
